using config map to test

diff --git a/charts/argo-cd/templates/redis/health-configmap.yaml b/charts/argo-cd/templates/redis/health-configmap.yaml
--- a/charts/argo-cd/templates/redis/health-configmap.yaml
+++ b/charts/argo-cd/templates/redis/health-configmap.yaml
@@ -34,4 +34,24 @@ data:
       exit 1
     fi
     echo "response=$response"
+  redis_entrypoint.sh: |
+    #!/bin/sh
+
+    echo "[INFO] Starting Redis with custom entrypoint..."
+
+    if [ -n "$REDIS_PASSWORD" ]; then
+      PASSWORD="$REDIS_PASSWORD"
+    elif [ -f /mnt/secrets/redis-password/_k8s_argocd_redis_password ]; then
+      PASSWORD=$(cat /mnt/secrets/redis-password/_k8s_argocd_redis_password | tr -d '\r\n')
+    else
+      echo "[ERROR] Redis password not found!"
+      exit 1
+    fi
+
+    echo "[INFO] Launching redis-server with requirepass"
+    exec redis-server \
+      --save "" \
+      --appendonly no \
+      --requirepass "$PASSWORD"
+
 {{- end }}
