testing argocd to use redis csi secret

diff --git a/charts/argo-cd/values.yaml b/charts/argo-cd/values.yaml
--- a/charts/argo-cd/values.yaml
+++ b/charts/argo-cd/values.yaml
@@ -1989,7 +1989,11 @@ server:
   args:
     - -c
     - |
-        REDIS_PASSWORD=""
+        REDIS_PASSWORD=$(cat /mnt/secrets/redis-password/_k8s_argocd_redis_password)
+        if [ -z "$REDIS_PASSWORD" ]; then
+          echo "Error: REDIS_PASSWORD is not set. Please provide a valid Redis password."
+          exit 1
+        fi
         exec /usr/local/bin/argocd-server --port=8080 --metrics-port=8083;
 
   # -- Additional command line arguments to pass to Argo CD server
